/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnerIndexRouteImport } from './routes/learner/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as LearnerRoadmapsRouteRouteImport } from './routes/learner/roadmaps/route'
import { Route as LearnerFriendsRouteRouteImport } from './routes/learner/friends/route'
import { Route as LearnerCoursesRouteRouteImport } from './routes/learner/courses/route'
import { Route as LearnerAboutRouteRouteImport } from './routes/learner/about/route'
import { Route as LearnerRoadmapsIndexRouteImport } from './routes/learner/roadmaps/index'
import { Route as LearnerFriendsIndexRouteImport } from './routes/learner/friends/index'
import { Route as LearnerCoursesIndexRouteImport } from './routes/learner/courses/index'
import { Route as LearnerAboutIndexRouteImport } from './routes/learner/about/index'
import { Route as LearnerCoursesPostIdRouteImport } from './routes/learner/courses/$postId'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerIndexRoute = LearnerIndexRouteImport.update({
  id: '/learner/',
  path: '/learner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoadmapsRouteRoute = LearnerRoadmapsRouteRouteImport.update({
  id: '/learner/roadmaps',
  path: '/learner/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerFriendsRouteRoute = LearnerFriendsRouteRouteImport.update({
  id: '/learner/friends',
  path: '/learner/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerCoursesRouteRoute = LearnerCoursesRouteRouteImport.update({
  id: '/learner/courses',
  path: '/learner/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerAboutRouteRoute = LearnerAboutRouteRouteImport.update({
  id: '/learner/about',
  path: '/learner/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoadmapsIndexRoute = LearnerRoadmapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnerRoadmapsRouteRoute,
} as any)
const LearnerFriendsIndexRoute = LearnerFriendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnerFriendsRouteRoute,
} as any)
const LearnerCoursesIndexRoute = LearnerCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnerCoursesRouteRoute,
} as any)
const LearnerAboutIndexRoute = LearnerAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnerAboutRouteRoute,
} as any)
const LearnerCoursesPostIdRoute = LearnerCoursesPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => LearnerCoursesRouteRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/learner/about': typeof LearnerAboutRouteRouteWithChildren
  '/learner/courses': typeof LearnerCoursesRouteRouteWithChildren
  '/learner/friends': typeof LearnerFriendsRouteRouteWithChildren
  '/learner/roadmaps': typeof LearnerRoadmapsRouteRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/learner/': typeof LearnerIndexRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/learner/courses/$postId': typeof LearnerCoursesPostIdRoute
  '/learner/about/': typeof LearnerAboutIndexRoute
  '/learner/courses/': typeof LearnerCoursesIndexRoute
  '/learner/friends/': typeof LearnerFriendsIndexRoute
  '/learner/roadmaps/': typeof LearnerRoadmapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/learner': typeof LearnerIndexRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/learner/courses/$postId': typeof LearnerCoursesPostIdRoute
  '/learner/about': typeof LearnerAboutIndexRoute
  '/learner/courses': typeof LearnerCoursesIndexRoute
  '/learner/friends': typeof LearnerFriendsIndexRoute
  '/learner/roadmaps': typeof LearnerRoadmapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/learner/about': typeof LearnerAboutRouteRouteWithChildren
  '/learner/courses': typeof LearnerCoursesRouteRouteWithChildren
  '/learner/friends': typeof LearnerFriendsRouteRouteWithChildren
  '/learner/roadmaps': typeof LearnerRoadmapsRouteRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/learner/': typeof LearnerIndexRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/learner/courses/$postId': typeof LearnerCoursesPostIdRoute
  '/learner/about/': typeof LearnerAboutIndexRoute
  '/learner/courses/': typeof LearnerCoursesIndexRoute
  '/learner/friends/': typeof LearnerFriendsIndexRoute
  '/learner/roadmaps/': typeof LearnerRoadmapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/redirect'
    | '/learner/about'
    | '/learner/courses'
    | '/learner/friends'
    | '/learner/roadmaps'
    | '/api/users'
    | '/learner/'
    | '/api/users/$id'
    | '/learner/courses/$postId'
    | '/learner/about/'
    | '/learner/courses/'
    | '/learner/friends/'
    | '/learner/roadmaps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/redirect'
    | '/api/users'
    | '/learner'
    | '/api/users/$id'
    | '/learner/courses/$postId'
    | '/learner/about'
    | '/learner/courses'
    | '/learner/friends'
    | '/learner/roadmaps'
  id:
    | '__root__'
    | '/'
    | '/deferred'
    | '/redirect'
    | '/learner/about'
    | '/learner/courses'
    | '/learner/friends'
    | '/learner/roadmaps'
    | '/api/users'
    | '/learner/'
    | '/api/users/$id'
    | '/learner/courses/$postId'
    | '/learner/about/'
    | '/learner/courses/'
    | '/learner/friends/'
    | '/learner/roadmaps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeferredRoute: typeof DeferredRoute
  RedirectRoute: typeof RedirectRoute
  LearnerAboutRouteRoute: typeof LearnerAboutRouteRouteWithChildren
  LearnerCoursesRouteRoute: typeof LearnerCoursesRouteRouteWithChildren
  LearnerFriendsRouteRoute: typeof LearnerFriendsRouteRouteWithChildren
  LearnerRoadmapsRouteRoute: typeof LearnerRoadmapsRouteRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  LearnerIndexRoute: typeof LearnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/': {
      id: '/learner/'
      path: '/learner'
      fullPath: '/learner/'
      preLoaderRoute: typeof LearnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/roadmaps': {
      id: '/learner/roadmaps'
      path: '/learner/roadmaps'
      fullPath: '/learner/roadmaps'
      preLoaderRoute: typeof LearnerRoadmapsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/friends': {
      id: '/learner/friends'
      path: '/learner/friends'
      fullPath: '/learner/friends'
      preLoaderRoute: typeof LearnerFriendsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/courses': {
      id: '/learner/courses'
      path: '/learner/courses'
      fullPath: '/learner/courses'
      preLoaderRoute: typeof LearnerCoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/about': {
      id: '/learner/about'
      path: '/learner/about'
      fullPath: '/learner/about'
      preLoaderRoute: typeof LearnerAboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/roadmaps/': {
      id: '/learner/roadmaps/'
      path: '/'
      fullPath: '/learner/roadmaps/'
      preLoaderRoute: typeof LearnerRoadmapsIndexRouteImport
      parentRoute: typeof LearnerRoadmapsRouteRoute
    }
    '/learner/friends/': {
      id: '/learner/friends/'
      path: '/'
      fullPath: '/learner/friends/'
      preLoaderRoute: typeof LearnerFriendsIndexRouteImport
      parentRoute: typeof LearnerFriendsRouteRoute
    }
    '/learner/courses/': {
      id: '/learner/courses/'
      path: '/'
      fullPath: '/learner/courses/'
      preLoaderRoute: typeof LearnerCoursesIndexRouteImport
      parentRoute: typeof LearnerCoursesRouteRoute
    }
    '/learner/about/': {
      id: '/learner/about/'
      path: '/'
      fullPath: '/learner/about/'
      preLoaderRoute: typeof LearnerAboutIndexRouteImport
      parentRoute: typeof LearnerAboutRouteRoute
    }
    '/learner/courses/$postId': {
      id: '/learner/courses/$postId'
      path: '/$postId'
      fullPath: '/learner/courses/$postId'
      preLoaderRoute: typeof LearnerCoursesPostIdRouteImport
      parentRoute: typeof LearnerCoursesRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
  }
}

interface LearnerAboutRouteRouteChildren {
  LearnerAboutIndexRoute: typeof LearnerAboutIndexRoute
}

const LearnerAboutRouteRouteChildren: LearnerAboutRouteRouteChildren = {
  LearnerAboutIndexRoute: LearnerAboutIndexRoute,
}

const LearnerAboutRouteRouteWithChildren =
  LearnerAboutRouteRoute._addFileChildren(LearnerAboutRouteRouteChildren)

interface LearnerCoursesRouteRouteChildren {
  LearnerCoursesPostIdRoute: typeof LearnerCoursesPostIdRoute
  LearnerCoursesIndexRoute: typeof LearnerCoursesIndexRoute
}

const LearnerCoursesRouteRouteChildren: LearnerCoursesRouteRouteChildren = {
  LearnerCoursesPostIdRoute: LearnerCoursesPostIdRoute,
  LearnerCoursesIndexRoute: LearnerCoursesIndexRoute,
}

const LearnerCoursesRouteRouteWithChildren =
  LearnerCoursesRouteRoute._addFileChildren(LearnerCoursesRouteRouteChildren)

interface LearnerFriendsRouteRouteChildren {
  LearnerFriendsIndexRoute: typeof LearnerFriendsIndexRoute
}

const LearnerFriendsRouteRouteChildren: LearnerFriendsRouteRouteChildren = {
  LearnerFriendsIndexRoute: LearnerFriendsIndexRoute,
}

const LearnerFriendsRouteRouteWithChildren =
  LearnerFriendsRouteRoute._addFileChildren(LearnerFriendsRouteRouteChildren)

interface LearnerRoadmapsRouteRouteChildren {
  LearnerRoadmapsIndexRoute: typeof LearnerRoadmapsIndexRoute
}

const LearnerRoadmapsRouteRouteChildren: LearnerRoadmapsRouteRouteChildren = {
  LearnerRoadmapsIndexRoute: LearnerRoadmapsIndexRoute,
}

const LearnerRoadmapsRouteRouteWithChildren =
  LearnerRoadmapsRouteRoute._addFileChildren(LearnerRoadmapsRouteRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeferredRoute: DeferredRoute,
  RedirectRoute: RedirectRoute,
  LearnerAboutRouteRoute: LearnerAboutRouteRouteWithChildren,
  LearnerCoursesRouteRoute: LearnerCoursesRouteRouteWithChildren,
  LearnerFriendsRouteRoute: LearnerFriendsRouteRouteWithChildren,
  LearnerRoadmapsRouteRoute: LearnerRoadmapsRouteRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  LearnerIndexRoute: LearnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
