/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RedirectRouteImport } from "./routes/redirect";
import { Route as DeferredRouteImport } from "./routes/deferred";
import { Route as LearnerRouteRouteImport } from "./routes/learner/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LearnerIndexRouteImport } from "./routes/learner/index";
import { Route as LearnerDashboardRouteImport } from "./routes/learner/dashboard";
import { Route as ApiUsersRouteImport } from "./routes/api/users";
import { Route as LearnerUserRouteRouteImport } from "./routes/learner/user/route";
import { Route as LearnerRoadmapsRouteRouteImport } from "./routes/learner/roadmaps/route";
import { Route as LearnerFriendsRouteRouteImport } from "./routes/learner/friends/route";
import { Route as LearnerCoursesRouteRouteImport } from "./routes/learner/courses/route";
import { Route as LearnerAboutRouteRouteImport } from "./routes/learner/about/route";
import { Route as LearnerSearchIndexRouteImport } from "./routes/learner/search/index";
import { Route as LearnerRoadmapsIndexRouteImport } from "./routes/learner/roadmaps/index";
import { Route as LearnerFriendsIndexRouteImport } from "./routes/learner/friends/index";
import { Route as LearnerCoursesIndexRouteImport } from "./routes/learner/courses/index";
import { Route as LearnerAboutIndexRouteImport } from "./routes/learner/about/index";
import { Route as LearnerUserUserIdRouteImport } from "./routes/learner/user/$userId";
import { Route as LearnerRoadmapsRoadmapIdRouteImport } from "./routes/learner/roadmaps/$roadmapId";
import { Route as LearnerCoursesPostIdRouteImport } from "./routes/learner/courses/$postId";
import { Route as ApiUsersIdRouteImport } from "./routes/api/users.$id";
import { Route as authLearnerVerifyEmailRouteImport } from "./routes/(auth)/learner.verify-email";
import { Route as authLearnerSignUpRouteImport } from "./routes/(auth)/learner.sign-up";
import { Route as authLearnerLogInRouteImport } from "./routes/(auth)/learner.log-in";
import { Route as authLearnerForgotPasswordRouteImport } from "./routes/(auth)/learner.forgot-password";

const RedirectRoute = RedirectRouteImport.update({
  id: "/redirect",
  path: "/redirect",
  getParentRoute: () => rootRouteImport,
} as any);
const DeferredRoute = DeferredRouteImport.update({
  id: "/deferred",
  path: "/deferred",
  getParentRoute: () => rootRouteImport,
} as any);
const LearnerRouteRoute = LearnerRouteRouteImport.update({
  id: "/learner",
  path: "/learner",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LearnerIndexRoute = LearnerIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: "/api/users",
  path: "/api/users",
  getParentRoute: () => rootRouteImport,
} as any);
const LearnerUserRouteRoute = LearnerUserRouteRouteImport.update({
  id: "/user",
  path: "/user",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const LearnerRoadmapsRouteRoute = LearnerRoadmapsRouteRouteImport.update({
  id: "/roadmaps",
  path: "/roadmaps",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const LearnerFriendsRouteRoute = LearnerFriendsRouteRouteImport.update({
  id: "/friends",
  path: "/friends",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const LearnerCoursesRouteRoute = LearnerCoursesRouteRouteImport.update({
  id: "/courses",
  path: "/courses",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const LearnerAboutRouteRoute = LearnerAboutRouteRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const LearnerSearchIndexRoute = LearnerSearchIndexRouteImport.update({
  id: "/search/",
  path: "/search/",
  getParentRoute: () => LearnerRouteRoute,
} as any);
const LearnerRoadmapsIndexRoute = LearnerRoadmapsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LearnerRoadmapsRouteRoute,
} as any);
const LearnerFriendsIndexRoute = LearnerFriendsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LearnerFriendsRouteRoute,
} as any);
const LearnerCoursesIndexRoute = LearnerCoursesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LearnerCoursesRouteRoute,
} as any);
const LearnerAboutIndexRoute = LearnerAboutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LearnerAboutRouteRoute,
} as any);
const LearnerUserUserIdRoute = LearnerUserUserIdRouteImport.update({
  id: "/$userId",
  path: "/$userId",
  getParentRoute: () => LearnerUserRouteRoute,
} as any);
const LearnerRoadmapsRoadmapIdRoute =
  LearnerRoadmapsRoadmapIdRouteImport.update({
    id: "/$roadmapId",
    path: "/$roadmapId",
    getParentRoute: () => LearnerRoadmapsRouteRoute,
  } as any);
const LearnerCoursesPostIdRoute = LearnerCoursesPostIdRouteImport.update({
  id: "/$postId",
  path: "/$postId",
  getParentRoute: () => LearnerCoursesRouteRoute,
} as any);
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiUsersRoute,
} as any);
const authLearnerVerifyEmailRoute = authLearnerVerifyEmailRouteImport.update({
  id: "/(auth)/learner/verify-email",
  path: "/learner/verify-email",
  getParentRoute: () => rootRouteImport,
} as any);
const authLearnerSignUpRoute = authLearnerSignUpRouteImport.update({
  id: "/(auth)/learner/sign-up",
  path: "/learner/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const authLearnerLogInRoute = authLearnerLogInRouteImport.update({
  id: "/(auth)/learner/log-in",
  path: "/learner/log-in",
  getParentRoute: () => rootRouteImport,
} as any);
const authLearnerForgotPasswordRoute =
  authLearnerForgotPasswordRouteImport.update({
    id: "/(auth)/learner/forgot-password",
    path: "/learner/forgot-password",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/learner": typeof LearnerRouteRouteWithChildren;
  "/deferred": typeof DeferredRoute;
  "/redirect": typeof RedirectRoute;
  "/learner/about": typeof LearnerAboutRouteRouteWithChildren;
  "/learner/courses": typeof LearnerCoursesRouteRouteWithChildren;
  "/learner/friends": typeof LearnerFriendsRouteRouteWithChildren;
  "/learner/roadmaps": typeof LearnerRoadmapsRouteRouteWithChildren;
  "/learner/user": typeof LearnerUserRouteRouteWithChildren;
  "/api/users": typeof ApiUsersRouteWithChildren;
  "/learner/dashboard": typeof LearnerDashboardRoute;
  "/learner/": typeof LearnerIndexRoute;
  "/learner/forgot-password": typeof authLearnerForgotPasswordRoute;
  "/learner/log-in": typeof authLearnerLogInRoute;
  "/learner/sign-up": typeof authLearnerSignUpRoute;
  "/learner/verify-email": typeof authLearnerVerifyEmailRoute;
  "/api/users/$id": typeof ApiUsersIdRoute;
  "/learner/courses/$postId": typeof LearnerCoursesPostIdRoute;
  "/learner/roadmaps/$roadmapId": typeof LearnerRoadmapsRoadmapIdRoute;
  "/learner/user/$userId": typeof LearnerUserUserIdRoute;
  "/learner/about/": typeof LearnerAboutIndexRoute;
  "/learner/courses/": typeof LearnerCoursesIndexRoute;
  "/learner/friends/": typeof LearnerFriendsIndexRoute;
  "/learner/roadmaps/": typeof LearnerRoadmapsIndexRoute;
  "/learner/search/": typeof LearnerSearchIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/deferred": typeof DeferredRoute;
  "/redirect": typeof RedirectRoute;
  "/learner/user": typeof LearnerUserRouteRouteWithChildren;
  "/api/users": typeof ApiUsersRouteWithChildren;
  "/learner/dashboard": typeof LearnerDashboardRoute;
  "/learner": typeof LearnerIndexRoute;
  "/learner/forgot-password": typeof authLearnerForgotPasswordRoute;
  "/learner/log-in": typeof authLearnerLogInRoute;
  "/learner/sign-up": typeof authLearnerSignUpRoute;
  "/learner/verify-email": typeof authLearnerVerifyEmailRoute;
  "/api/users/$id": typeof ApiUsersIdRoute;
  "/learner/courses/$postId": typeof LearnerCoursesPostIdRoute;
  "/learner/roadmaps/$roadmapId": typeof LearnerRoadmapsRoadmapIdRoute;
  "/learner/user/$userId": typeof LearnerUserUserIdRoute;
  "/learner/about": typeof LearnerAboutIndexRoute;
  "/learner/courses": typeof LearnerCoursesIndexRoute;
  "/learner/friends": typeof LearnerFriendsIndexRoute;
  "/learner/roadmaps": typeof LearnerRoadmapsIndexRoute;
  "/learner/search": typeof LearnerSearchIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/learner": typeof LearnerRouteRouteWithChildren;
  "/deferred": typeof DeferredRoute;
  "/redirect": typeof RedirectRoute;
  "/learner/about": typeof LearnerAboutRouteRouteWithChildren;
  "/learner/courses": typeof LearnerCoursesRouteRouteWithChildren;
  "/learner/friends": typeof LearnerFriendsRouteRouteWithChildren;
  "/learner/roadmaps": typeof LearnerRoadmapsRouteRouteWithChildren;
  "/learner/user": typeof LearnerUserRouteRouteWithChildren;
  "/api/users": typeof ApiUsersRouteWithChildren;
  "/learner/dashboard": typeof LearnerDashboardRoute;
  "/learner/": typeof LearnerIndexRoute;
  "/(auth)/learner/forgot-password": typeof authLearnerForgotPasswordRoute;
  "/(auth)/learner/log-in": typeof authLearnerLogInRoute;
  "/(auth)/learner/sign-up": typeof authLearnerSignUpRoute;
  "/(auth)/learner/verify-email": typeof authLearnerVerifyEmailRoute;
  "/api/users/$id": typeof ApiUsersIdRoute;
  "/learner/courses/$postId": typeof LearnerCoursesPostIdRoute;
  "/learner/roadmaps/$roadmapId": typeof LearnerRoadmapsRoadmapIdRoute;
  "/learner/user/$userId": typeof LearnerUserUserIdRoute;
  "/learner/about/": typeof LearnerAboutIndexRoute;
  "/learner/courses/": typeof LearnerCoursesIndexRoute;
  "/learner/friends/": typeof LearnerFriendsIndexRoute;
  "/learner/roadmaps/": typeof LearnerRoadmapsIndexRoute;
  "/learner/search/": typeof LearnerSearchIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/learner"
    | "/deferred"
    | "/redirect"
    | "/learner/about"
    | "/learner/courses"
    | "/learner/friends"
    | "/learner/roadmaps"
    | "/learner/user"
    | "/api/users"
    | "/learner/dashboard"
    | "/learner/"
    | "/learner/forgot-password"
    | "/learner/log-in"
    | "/learner/sign-up"
    | "/learner/verify-email"
    | "/api/users/$id"
    | "/learner/courses/$postId"
    | "/learner/roadmaps/$roadmapId"
    | "/learner/user/$userId"
    | "/learner/about/"
    | "/learner/courses/"
    | "/learner/friends/"
    | "/learner/roadmaps/"
    | "/learner/search/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/deferred"
    | "/redirect"
    | "/learner/user"
    | "/api/users"
    | "/learner/dashboard"
    | "/learner"
    | "/learner/forgot-password"
    | "/learner/log-in"
    | "/learner/sign-up"
    | "/learner/verify-email"
    | "/api/users/$id"
    | "/learner/courses/$postId"
    | "/learner/roadmaps/$roadmapId"
    | "/learner/user/$userId"
    | "/learner/about"
    | "/learner/courses"
    | "/learner/friends"
    | "/learner/roadmaps"
    | "/learner/search";
  id:
    | "__root__"
    | "/"
    | "/learner"
    | "/deferred"
    | "/redirect"
    | "/learner/about"
    | "/learner/courses"
    | "/learner/friends"
    | "/learner/roadmaps"
    | "/learner/user"
    | "/api/users"
    | "/learner/dashboard"
    | "/learner/"
    | "/(auth)/learner/forgot-password"
    | "/(auth)/learner/log-in"
    | "/(auth)/learner/sign-up"
    | "/(auth)/learner/verify-email"
    | "/api/users/$id"
    | "/learner/courses/$postId"
    | "/learner/roadmaps/$roadmapId"
    | "/learner/user/$userId"
    | "/learner/about/"
    | "/learner/courses/"
    | "/learner/friends/"
    | "/learner/roadmaps/"
    | "/learner/search/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LearnerRouteRoute: typeof LearnerRouteRouteWithChildren;
  DeferredRoute: typeof DeferredRoute;
  RedirectRoute: typeof RedirectRoute;
  ApiUsersRoute: typeof ApiUsersRouteWithChildren;
  authLearnerForgotPasswordRoute: typeof authLearnerForgotPasswordRoute;
  authLearnerLogInRoute: typeof authLearnerLogInRoute;
  authLearnerSignUpRoute: typeof authLearnerSignUpRoute;
  authLearnerVerifyEmailRoute: typeof authLearnerVerifyEmailRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/redirect": {
      id: "/redirect";
      path: "/redirect";
      fullPath: "/redirect";
      preLoaderRoute: typeof RedirectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/deferred": {
      id: "/deferred";
      path: "/deferred";
      fullPath: "/deferred";
      preLoaderRoute: typeof DeferredRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/learner": {
      id: "/learner";
      path: "/learner";
      fullPath: "/learner";
      preLoaderRoute: typeof LearnerRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/learner/": {
      id: "/learner/";
      path: "/";
      fullPath: "/learner/";
      preLoaderRoute: typeof LearnerIndexRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/learner/dashboard": {
      id: "/learner/dashboard";
      path: "/dashboard";
      fullPath: "/learner/dashboard";
      preLoaderRoute: typeof LearnerDashboardRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/api/users": {
      id: "/api/users";
      path: "/api/users";
      fullPath: "/api/users";
      preLoaderRoute: typeof ApiUsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/learner/user": {
      id: "/learner/user";
      path: "/user";
      fullPath: "/learner/user";
      preLoaderRoute: typeof LearnerUserRouteRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/learner/roadmaps": {
      id: "/learner/roadmaps";
      path: "/roadmaps";
      fullPath: "/learner/roadmaps";
      preLoaderRoute: typeof LearnerRoadmapsRouteRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/learner/friends": {
      id: "/learner/friends";
      path: "/friends";
      fullPath: "/learner/friends";
      preLoaderRoute: typeof LearnerFriendsRouteRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/learner/courses": {
      id: "/learner/courses";
      path: "/courses";
      fullPath: "/learner/courses";
      preLoaderRoute: typeof LearnerCoursesRouteRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/learner/about": {
      id: "/learner/about";
      path: "/about";
      fullPath: "/learner/about";
      preLoaderRoute: typeof LearnerAboutRouteRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/learner/search/": {
      id: "/learner/search/";
      path: "/search";
      fullPath: "/learner/search/";
      preLoaderRoute: typeof LearnerSearchIndexRouteImport;
      parentRoute: typeof LearnerRouteRoute;
    };
    "/learner/roadmaps/": {
      id: "/learner/roadmaps/";
      path: "/";
      fullPath: "/learner/roadmaps/";
      preLoaderRoute: typeof LearnerRoadmapsIndexRouteImport;
      parentRoute: typeof LearnerRoadmapsRouteRoute;
    };
    "/learner/friends/": {
      id: "/learner/friends/";
      path: "/";
      fullPath: "/learner/friends/";
      preLoaderRoute: typeof LearnerFriendsIndexRouteImport;
      parentRoute: typeof LearnerFriendsRouteRoute;
    };
    "/learner/courses/": {
      id: "/learner/courses/";
      path: "/";
      fullPath: "/learner/courses/";
      preLoaderRoute: typeof LearnerCoursesIndexRouteImport;
      parentRoute: typeof LearnerCoursesRouteRoute;
    };
    "/learner/about/": {
      id: "/learner/about/";
      path: "/";
      fullPath: "/learner/about/";
      preLoaderRoute: typeof LearnerAboutIndexRouteImport;
      parentRoute: typeof LearnerAboutRouteRoute;
    };
    "/learner/user/$userId": {
      id: "/learner/user/$userId";
      path: "/$userId";
      fullPath: "/learner/user/$userId";
      preLoaderRoute: typeof LearnerUserUserIdRouteImport;
      parentRoute: typeof LearnerUserRouteRoute;
    };
    "/learner/roadmaps/$roadmapId": {
      id: "/learner/roadmaps/$roadmapId";
      path: "/$roadmapId";
      fullPath: "/learner/roadmaps/$roadmapId";
      preLoaderRoute: typeof LearnerRoadmapsRoadmapIdRouteImport;
      parentRoute: typeof LearnerRoadmapsRouteRoute;
    };
    "/learner/courses/$postId": {
      id: "/learner/courses/$postId";
      path: "/$postId";
      fullPath: "/learner/courses/$postId";
      preLoaderRoute: typeof LearnerCoursesPostIdRouteImport;
      parentRoute: typeof LearnerCoursesRouteRoute;
    };
    "/api/users/$id": {
      id: "/api/users/$id";
      path: "/$id";
      fullPath: "/api/users/$id";
      preLoaderRoute: typeof ApiUsersIdRouteImport;
      parentRoute: typeof ApiUsersRoute;
    };
    "/(auth)/learner/verify-email": {
      id: "/(auth)/learner/verify-email";
      path: "/learner/verify-email";
      fullPath: "/learner/verify-email";
      preLoaderRoute: typeof authLearnerVerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/learner/sign-up": {
      id: "/(auth)/learner/sign-up";
      path: "/learner/sign-up";
      fullPath: "/learner/sign-up";
      preLoaderRoute: typeof authLearnerSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/learner/log-in": {
      id: "/(auth)/learner/log-in";
      path: "/learner/log-in";
      fullPath: "/learner/log-in";
      preLoaderRoute: typeof authLearnerLogInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/learner/forgot-password": {
      id: "/(auth)/learner/forgot-password";
      path: "/learner/forgot-password";
      fullPath: "/learner/forgot-password";
      preLoaderRoute: typeof authLearnerForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface LearnerAboutRouteRouteChildren {
  LearnerAboutIndexRoute: typeof LearnerAboutIndexRoute;
}

const LearnerAboutRouteRouteChildren: LearnerAboutRouteRouteChildren = {
  LearnerAboutIndexRoute: LearnerAboutIndexRoute,
};

const LearnerAboutRouteRouteWithChildren =
  LearnerAboutRouteRoute._addFileChildren(LearnerAboutRouteRouteChildren);

interface LearnerCoursesRouteRouteChildren {
  LearnerCoursesPostIdRoute: typeof LearnerCoursesPostIdRoute;
  LearnerCoursesIndexRoute: typeof LearnerCoursesIndexRoute;
}

const LearnerCoursesRouteRouteChildren: LearnerCoursesRouteRouteChildren = {
  LearnerCoursesPostIdRoute: LearnerCoursesPostIdRoute,
  LearnerCoursesIndexRoute: LearnerCoursesIndexRoute,
};

const LearnerCoursesRouteRouteWithChildren =
  LearnerCoursesRouteRoute._addFileChildren(LearnerCoursesRouteRouteChildren);

interface LearnerFriendsRouteRouteChildren {
  LearnerFriendsIndexRoute: typeof LearnerFriendsIndexRoute;
}

const LearnerFriendsRouteRouteChildren: LearnerFriendsRouteRouteChildren = {
  LearnerFriendsIndexRoute: LearnerFriendsIndexRoute,
};

const LearnerFriendsRouteRouteWithChildren =
  LearnerFriendsRouteRoute._addFileChildren(LearnerFriendsRouteRouteChildren);

interface LearnerRoadmapsRouteRouteChildren {
  LearnerRoadmapsRoadmapIdRoute: typeof LearnerRoadmapsRoadmapIdRoute;
  LearnerRoadmapsIndexRoute: typeof LearnerRoadmapsIndexRoute;
}

const LearnerRoadmapsRouteRouteChildren: LearnerRoadmapsRouteRouteChildren = {
  LearnerRoadmapsRoadmapIdRoute: LearnerRoadmapsRoadmapIdRoute,
  LearnerRoadmapsIndexRoute: LearnerRoadmapsIndexRoute,
};

const LearnerRoadmapsRouteRouteWithChildren =
  LearnerRoadmapsRouteRoute._addFileChildren(LearnerRoadmapsRouteRouteChildren);

interface LearnerUserRouteRouteChildren {
  LearnerUserUserIdRoute: typeof LearnerUserUserIdRoute;
}

const LearnerUserRouteRouteChildren: LearnerUserRouteRouteChildren = {
  LearnerUserUserIdRoute: LearnerUserUserIdRoute,
};

const LearnerUserRouteRouteWithChildren =
  LearnerUserRouteRoute._addFileChildren(LearnerUserRouteRouteChildren);

interface LearnerRouteRouteChildren {
  LearnerAboutRouteRoute: typeof LearnerAboutRouteRouteWithChildren;
  LearnerCoursesRouteRoute: typeof LearnerCoursesRouteRouteWithChildren;
  LearnerFriendsRouteRoute: typeof LearnerFriendsRouteRouteWithChildren;
  LearnerRoadmapsRouteRoute: typeof LearnerRoadmapsRouteRouteWithChildren;
  LearnerUserRouteRoute: typeof LearnerUserRouteRouteWithChildren;
  LearnerDashboardRoute: typeof LearnerDashboardRoute;
  LearnerIndexRoute: typeof LearnerIndexRoute;
  LearnerSearchIndexRoute: typeof LearnerSearchIndexRoute;
}

const LearnerRouteRouteChildren: LearnerRouteRouteChildren = {
  LearnerAboutRouteRoute: LearnerAboutRouteRouteWithChildren,
  LearnerCoursesRouteRoute: LearnerCoursesRouteRouteWithChildren,
  LearnerFriendsRouteRoute: LearnerFriendsRouteRouteWithChildren,
  LearnerRoadmapsRouteRoute: LearnerRoadmapsRouteRouteWithChildren,
  LearnerUserRouteRoute: LearnerUserRouteRouteWithChildren,
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearnerIndexRoute: LearnerIndexRoute,
  LearnerSearchIndexRoute: LearnerSearchIndexRoute,
};

const LearnerRouteRouteWithChildren = LearnerRouteRoute._addFileChildren(
  LearnerRouteRouteChildren,
);

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute;
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
};

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnerRouteRoute: LearnerRouteRouteWithChildren,
  DeferredRoute: DeferredRoute,
  RedirectRoute: RedirectRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  authLearnerForgotPasswordRoute: authLearnerForgotPasswordRoute,
  authLearnerLogInRoute: authLearnerLogInRoute,
  authLearnerSignUpRoute: authLearnerSignUpRoute,
  authLearnerVerifyEmailRoute: authLearnerVerifyEmailRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
